apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hipstershop-vs
spec:
  gateways:
  - hipstershop-gateway
  hosts:
  - productcatalogservice
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: productcatalogservice
        subset: v1
      weight: 50
    - destination:
        host: productcatalogservice
        subset: v2
      weight: 50