apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-istio-1-10-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/willowmck/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/instances/overlays/platform/istio/gm-istio/1.10.3/multicluster/mesh1-cluster1
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true