apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod-1-9-5.istio-system.svc:15012
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mesh":"defaultConfig:\n  discoveryAddress: istiod-1-9-5.istio-system.svc:15012\n  proxyMetadata:\n    ISTIO_META_DNS_CAPTURE: \"true\"\n  tracing:\n    zipkin:\n      address: zipkin.istio-system:9411\nenablePrometheusMerge: true\nrootNamespace: istio-system\ntrustDomain: cluster.local","meshNetworks":"networks: {}"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"control-plane","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"1-9-5","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.9.5","release":"istio"},"name":"istio","namespace":"istio-system"}}
  labels:
    install.operator.istio.io/owning-resource: control-plane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: 1-9-5
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.9.5
    release: istio
  name: istio
  namespace: istio-system