# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../../../../instances/overlays/platform/kiali/

resources:
- 1-9-5-configmap.yaml
- monitor-control-plane.yaml
- monitor-data-plane.yaml