apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../istio/virtualservices/frontend/

resources: 
- productcatalog-destination-rule.yaml
- productcatalog-vs-abort.yaml