apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-portal-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/instances/overlays/platform/gloo-portal/helm-customvalues
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #  - CreateNamespace=true