apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/instances/overlays/platform/istio/addons/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true