apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petstore-swagger-apiproduct-0-7-8
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/instances/overlays/frontend/petstore/swaggerapi/gloo-portal-0-7-8/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    #syncOptions:
    #- CreateNamespace=true
  #ignoreDifferences:
  #- group: apps
  #  kind: Deployment
  #  jsonPointers:
  #  - /spec/replicas
  #- group: route.openshift.io
  #  kind: Route
  #  jsonPointers:
  #  - /status