
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore-vs-regexmatch
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
         - regex: /[a-z]{5}
        routeAction:
          single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
        options:
          autoHostRewrite: true
