apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge
  namespace: argocd
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://storage.googleapis.com/solo-public-helm
    targetRevision: 1.8.0
    targetRevision: 1.7.7
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
