apiVersion: portal.gloo.solo.io/v1beta1
kind: User
metadata:
  name: developer1
  namespace: gloo-portal
spec:
  accessLevel:
    portals:
    - name: ecommerce-portal
      namespace: default
  basicAuth:
    passwordSecretKey: password
    passwordSecretName: developer1-password
    passwordSecretNamespace: gloo-portal
  username: developer1