apiVersion: portal.gloo.solo.io/v1beta1
kind: User
metadata:
  name: developer1
  namespace: gloo-portal
  labels:
    groups.portal.gloo.solo.io/gloo-portal.developers: "true"
spec:
  basicAuth:
    passwordSecretKey: password
    passwordSecretName: developer1-password
    passwordSecretNamespace: gloo-portal
  username: developer1