apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- petstore-v1.yaml
- petstore-v2.yaml
- petstore-openapi-v1-pets-apidoc.yaml 
- petstore-openapi-v1-users-apidoc.yaml
- petstore-openapi-v2-full-apidoc.yaml
- petstore-apiproduct.yaml    
- dev-envionment.yaml
- petstore-portal.yaml
- developer1-user.yaml

secretGenerator:
- name: developer1-password
  namespace: gloo-portal
  literals:
  - password=nothing