apiVersion: portal.gloo.solo.io/v1beta1
kind: APIDoc
metadata:
  name: petstore-openapi-v1-pets
  namespace: default
spec:
  openApi:
    content:
      fetchUrl: https://raw.githubusercontent.com/ably77/solo-testbed/main/gloo-portal/openapi-specs/petstore-openapi-v1-pets.json