# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../../../../../../../manifests/app/platform/istio/base/profiles/minimal/

# list of Resource Config to be Applied
resources:
- ingress-gateway.yaml
- istio-ingress-ns.yaml

patchesStrategicMerge:
- patches/ingress-gateway-revision.yaml