apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../../../manifests/app/frontend/hipstershop/base/productcatalog/0.2.4/

patchesStrategicMerge:
- patch/fix-delay.yaml