apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: bookinfo-v1-routetable
  namespace: bookinfo-v1
spec:
  routes:
    - matchers:
        - prefix: /
      options:
        prefixRewrite: '/'
      routeAction:
          single:
            upstream:
              name: bookinfo-v1-productpage-9080
              namespace: gloo-system