apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: bookinfo-beta-routetable
  namespace: bookinfo-beta
spec:
  routes:
    - matchers:
        - prefix: /beta
      options:
        prefixRewrite: '/'
      routeAction:
          single:
            upstream:
              name: bookinfo-beta-productpage-9080
              namespace: gloo-system