apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-routetable-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /v1
# ------------- Delegation action by reference A ------------------
        delegateAction:
          ref:
            name: 'httpbin-a-routetable'
            namespace: 'httpbin'
# ---------------------------------------------------------------
      - matchers:
          - prefix: /beta
# ------------- Delegation action by reference B ------------------
        delegateAction:
          ref:
            name: 'httpbin-b-routetable'
            namespace: 'httpbin'
# ---------------------------------------------------------------