apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo-routetable-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /v1
# ------------- Delegation action by reference A ------------------
        delegateAction:
          ref:
            name: 'bookinfo-v1-routetable'
            namespace: 'bookinfo-v1'