apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-oss-helm-customvalues
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/instances/overlays/platform/gloo-edge/oss/helm-customvalues/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true