apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalogservice-canary-dr
spec:
  host: [[ "productcatalogservice", "productcatalogservice-v2" ]]
  subsets: 
  - name: v1
    labels:
      version: "v0.2.3"
  - name: v2
    labels:
      version: "v0.2.4"