apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productcatalog-canary-vs
spec:
  hosts:
  - 'productcatalogservice.hipstershop.svc.cluster.local'
  http:
  - route:
    - destination:
        host: productcatalogservice-dr
        subset: v1
      weight: 100
    - destination:
        host: productcatalogservice-dr
        subset: v2
      weight: 0
    retries:
      attempts: 3
      perTryTimeout: 4s
    fault:
      delay:
        percent: 0
        fixedDelay: 10s
      