apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalogservice-dr
spec:
  host: productcatalogservice
  subsets: 
  - name: v1
    labels:
      version: "v0.1.3"
  - name: v2
    labels:
      version: "v0.2.4"