apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productcatalog-canary-vs
spec:
  hosts:
  - 'productcatalogservice'
  http:
  - route:
    - destination:
        host: productcatalogservice
        subset: v1
      weight: 0
    - destination:
        host: productcatalogservice
        subset: v2
      weight: 100
    retries:
      attempts: 3
      perTryTimeout: 2s
      