apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice-v2
spec:
  template:
    spec:
      containers:
        env:
        - name: PORT
          value: "3550"
        - name: EXTRA_LATENCY
          value: 0s