apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice-v2
spec:
  template:
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.4
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: EXTRA_LATENCY
          value: 0s