apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: grafana
    helm:
      values: |
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.8.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 

# Get the password
# kubectl get secret --namespace gloo-mesh grafana-helm -o jsonpath="{.data.admin-password}" | base64 --decode ; echo

# Access the UI
# export POD_NAME=$(kubectl get pods --namespace gloo-mesh -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}")
# kubectl --namespace gloo-mesh port-forward $(kubectl get pods --namespace gloo-mesh -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}") 3000

# For the moment, need to manually add the Prometheus data source at http://prometheus-server:80