apiVersion: devportal.solo.io/v1alpha1
kind: APIDoc
metadata:
  name: petstore-v2
  namespace: default
spec:
  openApi:
    content:
      fetchUrl: https://github.com/solo-io/workshops/raw/master/gloo-portal/swagger-petstore-v2.json