apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-global-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/environments/overlays/gloo-edge/global-config/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true