apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo-advanced-delegation-vs
  namespace: gloo-system
spec:
# ------------- enable tls ------------------
  sslConfig:
    secretRef:
      name: upstream-tls
# ---------------------------------------------------------------
  virtualHost:
    options:
# ------------- enable extauth ------------------
      extauth:
        configRef:
          name: keycloak-oauth
          namespace: gloo-system
# ------------- enable global ratelimit ------------------
      rateLimitConfigs:
        refs:
        - name: global-limit
          namespace: gloo-system
# ------------- enable waf ------------------
      waf:
        customInterventionMessage: 'Username should only contain letters'
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecRule ARGS:/username/ "[^a-zA-Z]" "t:none,phase:2,deny,id:6,log,msg:'allow only letters in username'"
# ---------------- Transformation ------------------          
      transformations:
        responseTransformation:
          transformationTemplate:
            parseBodyBehavior: DontParse
            body: 
              text: '{% if header(":status") == "429" %}<html><body style="background-color:powderblue;"><h1>Too many Requests!</h1><p>Try again after 10 seconds</p></body></html>{% else %}{{ body() }}{% endif %}'    
#---------------------------------------------------
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /v1
# ------------- Delegation action by reference A ------------------
        delegateAction:
          ref:
            name: 'bookinfo-v1-routetable'
            namespace: 'bookinfo-v1'
# ---------------------------------------------------------------
      - matchers:
          - prefix: /beta
# ------------- Delegation action by reference B ------------------
        delegateAction:
          ref:
            name: 'bookinfo-beta-routetable'
            namespace: 'bookinfo-beta'
# ---------------------------------------------------------------