apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo-routetable-vs
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system  
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
# ------------- Delegation action by reference A ------------------
        delegateAction:
          ref:
            name: 'bookinfo-v1-routetable'
            namespace: 'bookinfo-v1'