apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-agent-cluster1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: enterprise-agent
    helm:
      values: |
        relay:
          serverAddress: 172.18.1.1:9900
          authority: "cluster.local"
          cluster: cluster1
    repoURL: https://storage.googleapis.com/gloo-mesh-enterprise/enterprise-agent
    targetRevision: 1.1.0-beta20
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true