
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore-vs-headermatch
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'petstore.solo.io'
    routes:
      - matchers:
         - headers:
            - name: header1
              value: value1
           prefix: /
        routeAction:
          single:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
        options:
          autoHostRewrite: true
