
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore-vs-headermatch
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'petstore.solo.io'
    routes:
      - matchers:
         - headers:
            - name: header1
              value: value1
            - name: header2
            - name: header3
              regex: true
              value: "[a-z]{1}"
            - name: header4
              invertMatch: true
            - name: header5
              value: value5
              invertMatch: true
           prefix: /
        routeAction:
          single:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
        options:
          autoHostRewrite: true
