# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../../../../../../../manifests/app/platform/istio/base/profiles/default

patchesStrategicMerge:
- patches/version-1.10.2.yaml