apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-oss-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-mesh
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-mesh
    repoURL: 'https://storage.googleapis.com/gloo-mesh/gloo-mesh'
    targetRevision: 1.0.11
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true
