apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: kiali-operator
    repoURL: https://kiali.org/helm-charts
    helm:
      valueFiles:
      - values.yaml
    targetRevision: 1.29.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true