apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hipstershop-vs
spec:
  gateways:
  - hipstershop-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 80
        subset: v1
      weight: 0
    - destination:
        host: frontend
        port:
          number: 80
        subset: v2
      weight: 100