apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    discovered_by: kubernetesplugin
  name: httpbin-httpbin-8000
  namespace: httpbin
spec:
  discoveryMetadata:
    labels:
      app: httpbin
      service: httpbin
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    #serviceNamespace: default
    serviceNamespace: httpbin
    servicePort: 8000
    serviceSpec:
      rest:
        swaggerInfo:
          url: https://raw.githubusercontent.com/solo-io/solo-blog/main/zero-to-gateway/httpbin-openapi.json