apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sock-shop
spec:
  gateways:
  - sock-shop
  hosts:
  - '*'
  http:
  - route:
    - destination: 
        host: front-end
        port:
          number: 80