apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendationservice-delay
spec:
  hosts:
  - recommendationservice
  http:
  - match:
    - uri:
        prefix: /
    fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 10s
    route:
    - destination:
        host: recommendationservice
        subset: v1
  - route:
    - destination:
        host: recommendationservice
        subset: v1