apiVersion: devportal.solo.io/v1alpha1
kind: APIProduct
metadata:
  name: petstore
  namespace: default
spec:
  displayInfo: 
    description: Petstore Product
    title: Petstore Product
    image:
      fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  versions:
  - name: v1
    apis:
    - apiDoc:
        name: petstore-v1
        namespace: default
    tags:
      stable: {}
    defaultRoute:
      inlineRoute:
        backends:
        - kube:
            name: petstore-v1
            namespace: default
            port: 8080
  - name: v2
    apis:
    - apiDoc:
        name: petstore-v2
        namespace: default
    tags:
      stable: {}
    defaultRoute:
      inlineRoute:
        backends:
        - kube:
            name: petstore-v2
            namespace: default
            port: 8080