apiVersion: fed.gloo.solo.io/v1
kind: FederatedUpstream
metadata:
  name: default-service-bluegreen
  namespace: gloo-system
spec:
  placement:
    clusters:
      - cluster4
      - cluster5
    namespaces:
      - gloo-system
  template:
    metadata:
      name: default-service-bluegreen-8080
    spec:
      discoveryMetadata: {}
      healthChecks:
        - healthyThreshold: 1
          httpHealthCheck:
            path: /
          interval: 1s
          noTrafficInterval: 1s
          timeout: 1s
          unhealthyThreshold: 1
      kube:
        serviceName: service-bluegreen
        serviceNamespace: default
        servicePort: 8080
---
apiVersion: fed.gateway.solo.io/v1
kind: FederatedVirtualService
metadata:
  name: any-bluegreen
  namespace: gloo-system
spec:
  placement:
    clusters:
      - cluster4
      - cluster5
    namespaces:
      - gloo-system
  template:
    spec:
      virtualHost:
        domains:
        - '*'
        routes:
        - matchers:
          - prefix: /
          routeAction:
            single:
              upstream:
                name: default-service-bluegreen-8080
                namespace: gloo-system
    metadata:
      name: any-bluegreen