apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: petstore-portal
  namespace: default
spec:
  displayName: Petstore Portal
  description: The Developer Portal for the Petstore API
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages: []
  domains:
  - portal.petstore.com

  oidcAuth:
    callbackUrlPrefix: http://portal.petstore.com/
    # testing this
    clientId: e358633c-5352-4933-b3f4-df5ab68ac1c1
    #clientId: ${KEYCLOAK_CLIENT}
    clientSecret:
      name: petstore-portal-oidc-secret
      namespace: default
      key: client_secret
    groupClaimKey: group
    # testing this
    issuer: http://172.18.3.1:8080/auth/realms/master
    #issuer: ${KEYCLOAK_URL}/realms/master
  portalUrlPrefix: http://portal.petstore.com/

  publishedEnvironments:
  - name: dev
    namespace: default