apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-istio-components
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/solo-testbed-apps
    targetRevision: HEAD
    path: kustomize/instances/overlays/platform/knative/kn-istio-components/
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true